/** Shared palette for home ServicesSection + services page ServicesAccordion */

export const serviceCardThemes = [
  {
    cardBg: "bg-background-secondary",
    cardHover: "hover:bg-background-muted",
    cardActive: "ring-2 ring-accent/30 scale-[1.02]",
    text: "text-foreground",
    muted: "text-muted-foreground",
    num: "text-foreground/25",
    icon: "text-accent",
    divider: "bg-border",
    imgOverlay: "bg-white/10",
    panelBg: "bg-background-muted",
    tagBg: "border-border bg-background text-foreground",
    challengeDot: "bg-accent",
    outcomeCard: "border-border bg-background",
    processStep: "border-border bg-background-secondary text-foreground",
    processNum: "text-muted-foreground",
    ctaPrimary: "bg-foreground text-background",
    imageOverlay: "bg-black/10",
  },
  {
    cardBg: "bg-surface-dark",
    cardHover: "hover:bg-surface-elevated",
    cardActive: "ring-2 ring-accent/40 scale-[1.02]",
    text: "text-white",
    muted: "text-white/55",
    num: "text-white/25",
    icon: "text-accent",
    divider: "bg-white/15",
    imgOverlay: "bg-black/30",
    panelBg: "bg-surface-elevated",
    tagBg: "border-white/12 bg-white/8 text-white/80",
    challengeDot: "bg-accent",
    outcomeCard: "border-white/8 bg-white/5",
    processStep: "border-white/10 bg-white/6 text-white/80",
    processNum: "text-white/25",
    ctaPrimary: "bg-white text-zinc-950",
    imageOverlay: "bg-black/25",
  },
  {
    cardBg: "bg-accent-light",
    cardHover: "hover:bg-accent-light/80",
    cardActive: "ring-2 ring-accent/35 scale-[1.02]",
    text: "text-foreground",
    muted: "text-muted-foreground",
    num: "text-foreground/25",
    icon: "text-accent-dark",
    divider: "bg-border",
    imgOverlay: "bg-white/10",
    panelBg: "bg-background-secondary",
    tagBg: "border-border bg-background/80 text-foreground",
    challengeDot: "bg-accent-dark",
    outcomeCard: "border-border bg-background",
    processStep: "border-border bg-background text-foreground",
    processNum: "text-muted-foreground",
    ctaPrimary: "bg-foreground text-background",
    imageOverlay: "bg-black/10",
  },
] as const;

export type ServiceCardTheme = (typeof serviceCardThemes)[number];
